art-e-fact/RoboProp

roboprop/settings.py
roboprop_client/urls.py
roboprop_client/views.py
templates/base.html
templates/home.html
templates/mymodels.html
templates/partials/navbar.html

* Add gallery and categories
* use artefacts action color
* move container div to base.html
* shadows on gallery cards

Mymodels gallery (#8)

---

roboprop_client/tests.py
roboprop_client/urls.py
roboprop_client/views.py
templates/base.html
templates/components/_loading_placeholder.html
templates/components/_search-svg.html
templates/find-models.html
templates/mymodels.html
templates/partials/_navbar.html

* fuel gallery page
* search fuel
* cleanup templates
* move mymodels to /mymodels
* display fuel models as well
* fuel and mymodel cleanup
* refactor get_model_thumbnails
* search with cache

Search fuel (#16)

---

roboprop/settings.py
roboprop_client/tests.py
roboprop_client/urls.py
roboprop_client/views.py
templates/base.html
templates/login.html
templates/partials/_navbar.html
templates/register.html
templates/user-settings.html

Adds basic user auth (registration, login, change settings)

Add user auth

---

roboprop/settings.py
roboprop_client/tests.py
roboprop_client/urls.py
roboprop_client/views.py
templates/base.html
templates/login.html
templates/partials/_navbar.html
templates/register.html
templates/user-settings.html

* view and url logic
* html for login and registration
* login and logout  logic
* add user settings page
* success messages block
* login and user setting tests

Add user auth (#18)

---

roboprop_client/views.py
templates/components/_message_block.html
templates/login.html
templates/register.html
templates/user-settings.html

Use Django's built in messaging service

Make messaging into component

---

roboprop_client/views.py
templates/components/_message_block.html
templates/login.html
templates/register.html
templates/user-settings.html

* message block as component
* messages for login an register

Make messaging into component (#20)

---

package-lock.json
roboprop_client/views.py
templates/find-models.html

Moves all saved models to models folder rather than separate for local and fuel

remove fuelmodel directory calls

---

roboprop_client/tests.py
roboprop_client/views.py
templates/components/_upload_modal.html
templates/mymodels.html

* Allows for UI based upload, to then upload via POST call to roboprop server

Upload local models

---

roboprop_client/tests.py
roboprop_client/views.py
templates/components/_upload_modal.html
templates/mymodels.html

* Allow uploads
* Extract logic
* upload logic in modal
* move modal to component
* cleanup Css

Upload local models (#24)

---

roboprop_client/tests.py
roboprop_client/urls.py
roboprop_client/views.py
templates/components/_category_block.html
templates/components/_myrobots-svg.html
templates/find-models.html
templates/mymodel_detail.html
templates/mymodels.html
templates/myrobot_detail.html
templates/myrobots.html
templates/partials/_asset_gallery.html
templates/partials/_model_configuration.html
templates/partials/_navbar.html

* Adds myrobots page, ability to upload robot descriptions / controllers

Add upload robots

---

roboprop_client/tests.py
roboprop_client/utils.py
roboprop_client/views.py
templates/partials/_model_configuration.html

* Moves API requests to utils
* Combines POST logic for adding robots and models
* Removes logic to allow configuration changes in the browser.

Refactor api requests

---

roboprop_client/tests.py
roboprop_client/utils.py
roboprop_client/views.py
templates/partials/_model_configuration.html

* move requests to utils
* move upload file logic to utils
* remove logic to allow config to be amended

Refactor api requests (#28)

---

requirements.txt
roboprop_client/tests.py
roboprop_client/urls.py
roboprop_client/utils.py
roboprop_client/views.py
templates/add_metadata.html

* aws rekognition logic
* check thumbnails exist
* metadata passed to tagging view
* basic form for selecting tags
* create index.json
* save index.json to fileserver
* add roboprop server location of model
* make url safe
* combine categories and parent_categories

Suggested model tags (#33)

---

roboprop_client/tests.py
roboprop_client/utils.py
roboprop_client/views.py
templates/add_metadata.html

Allows the user to add their own metadata, not just what is suggested by aws rekognition

Add custom tags to index

---

roboprop_client/tests.py
roboprop_client/utils.py
roboprop_client/views.py
templates/add_metadata.html

* custom fields
* form spacing
* convert comma separated list to string
* fix upload test
* clarify tag list extension
* refactor custom fields logic

Add custom tags to index (#39)

---

.gitignore
requirements.txt
roboprop_client/demo.sdf.template
roboprop_client/export_model.py
roboprop_client/load_blenderproc.py
roboprop_client/tests.py
roboprop_client/utils.py
roboprop_client/views.py

* Seperate search into fuel and blendkit
* display blendkit results in browser
* seperate Fuel and Blendkit logic in html template
* seperate Fuel and Blendkit upload logic
* Unit Tests, blendkit tempoararily uploading thumbnail only
* add blendproc logic via subprocesS
* zip and upload to fileserver
* move zip creation and folder deltion to utils
* metadata index.json logic
* autotag blendkit models
* demo sdf template
* fix incorrect model url in index.json
* Export visuals from Blender as .GLB
* Remove debug code from demo template
---------

Convert blender to sdf (#38)

---

README.md

Moves readme usage section to wiki

Move Usage to Wiki

---

requirements.txt
roboprop_client/blender_scripts/export_glb.py
roboprop_client/blender_scripts/export_obj.py
roboprop_client/export_model.py
roboprop_client/load_blenderkit.py
roboprop_client/urls.py
roboprop_client/views.py
templates/mymodels.html

* Use blender directly instead of blenderproc Also, use JPEG textures in GLB exports to limit file sizes
* Rerun blenderkit conversions (#54)
* Allow reconversion of all current blendkit models
* cleanup css
---------

Use Blender directly instead of blenderproc (#53)

---

roboprop_client/views.py
templates/find-models.html

Allows asset base-id to be added directly.

Direct addition of blenderkit models

---

roboprop_client/views.py
templates/find-models.html

* JS to allow user direct input of assetbaseid
* Search by  asset base id for blenderkit
* search by asset-id
* cleanup

Direct addition of blenderkit models (#59)

---

roboprop_client/export_model.py

Adds very basic collision detection for the sdf models during blenderkit conversion process

add basic collision detection:

---

roboprop_client/load_blenderkit.py
roboprop_client/views.py

Lets user know of a bad api key / expired api key when using blenderkit to search for models

Error on bad api key

---

.gitignore
Dockerfile
docker-compose.yaml
example.env
nginx/Dockerfile
nginx/nginx.conf
requirements.txt
roboprop/settings.py

* Dockerize client
* add css build stage
* modify settings and example.env
* rename microservice to roboprop_client
* better clarification on compose volumes

Dockerize Roboprop_Client (#67)

---

roboprop_client/tests.py
roboprop_client/urls.py
roboprop_client/views.py
templates/find-models.html
templates/mymodels.html

basic naming clean up of my previously poorly written stuff. Private functions with a single underscore. and blendkit to blenderkit (no idea why i thought it was blendkit)

Code cleanup

---

.github/workflows/branches.yml
.github/workflows/callable_ci.yml
.github/workflows/development_deploy.yml
.github/workflows/main.yml

add github actions

---

Dockerfile

Allows for single Dockerfile build

single Dockerfile build:

---

roboprop_client/tests.py
roboprop_client/utils.py
roboprop_client/views.py

Makes all login session checked against the fileserver (dreamfactory) rather than an inbuilt storage session

Fileserver session checks

---

Dockerfile
roboprop/settings.py

bpy was failing in Docker, looks like it needs some extra dependencies

bpy dependencies plus black

---

roboprop_client/blender_scripts/export_fbx.py
roboprop_client/utils.py

Does some better cleanup on error (a failed post request when uploading a model), and also (main event) removes shape keys from models allowing for a larger percentage of models to be have collision meshes applied. 
Shape keys (should) only really affect visual meshes, so there is hopefully little harm in removing them for  the collision portion

Extra model compatibility

---

roboprop_client/blender_scripts/collisions.py
roboprop_client/blender_scripts/export_fbx.py
roboprop_client/blender_scripts/export_glb.py
roboprop_client/blender_scripts/export_obj.py
roboprop_client/export_model.py
roboprop_client/tests.py

if @azazdeaz  is happy with his testing, then we can merge and convert pre-existing models I think.
There is an issue on file size -> collision meshes generated can be rather large. Will make a separate issue on  this

Collision meshes all model types
